=== iTReprise/XML_Klimadaten_WS18-19/data/climateData.dtd
<!ELEMENT climateData (
  longitude,
  latitude,
  entry+
)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT entry (
  temperature,
  surface,
  solar,
  humidity
)>
<!ELEMENT temperature (
  curTemp,
  avgTemp,
  maxTemp,
  minTemp
)>
<!ELEMENT surface (
  avgSurTemp,
  maxSurTemp,
  minSurTemp
)>
<!ELEMENT solar (
  avgSolRad,
  maxSolRad,
  minSolRad
)>
<!ELEMENT humidity (
  avgRelHum
)>
<!ELEMENT curTemp (#PCDATA)>
<!ELEMENT avgTemp (#PCDATA)>
<!ELEMENT maxTemp (#PCDATA)>
<!ELEMENT minTemp (#PCDATA)>
<!ELEMENT avgSurTemp (#PCDATA)>
<!ELEMENT maxSurTemp (#PCDATA)>
<!ELEMENT minSurTemp (#PCDATA)>
<!ELEMENT avgSolRad (#PCDATA)>
<!ELEMENT maxSolRad (#PCDATA)>
<!ELEMENT minSolRad (#PCDATA)>
<!ELEMENT avgRelHum (#PCDATA)>

<!ATTLIST climateData locationID CDATA #REQUIRED>
<!ATTLIST climateData xmlns:xsi CDATA #REQUIRED>
<!ATTLIST climateData xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ATTLIST longitude unit CDATA #FIXED "decimal_degrees">
<!ATTLIST latitude unit CDATA #FIXED "decimal_degrees">
<!ATTLIST entry date CDATA #REQUIRED>
<!ATTLIST entry time CDATA #REQUIRED>
<!ATTLIST entry standard CDATA #FIXED "UTC">
<!ATTLIST curTemp unit CDATA #REQUIRED>
<!ATTLIST avgTemp unit CDATA #REQUIRED>
<!ATTLIST maxTemp unit CDATA #REQUIRED>
<!ATTLIST minTemp unit CDATA #REQUIRED>
<!ATTLIST avgSurTemp unit CDATA #REQUIRED>
<!ATTLIST maxSurTemp unit CDATA #REQUIRED>
<!ATTLIST minSurTemp unit CDATA #REQUIRED>
<!ATTLIST avgSolRad unit CDATA #REQUIRED>
<!ATTLIST maxSolRad unit CDATA #REQUIRED>
<!ATTLIST minSolRad unit CDATA #REQUIRED>
<!ATTLIST avgRelHum unit CDATA #REQUIRED>

=== iTReprise/XML_Klimadaten_WS18-19/drafts/xml_ohne_daten.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://www.imn.htwk-leipzig.de/~futku/climateData.xsl"?>
<!DOCTYPE climateData SYSTEM "http://www.imn.htwk-leipzig.de/~futku/climateData.dtd">
<climateData
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.imn.htwk-leipzig.de/~futku/climateData.xsd"
  locationID="94082">
  <longitude unit="decimal_degrees"></longitude>
  <latitude unit="decimal_degrees"></latitude>

  <entry date="yyyy.mm.dd" time="hh:mm" standard="UTC">
    <temperature>
      <curTemp unit="C" xsi:nil="false"></curTemp>
      <avgTemp unit="C" xsi:nil="false"></avgTemp>
      <maxTemp unit="C" xsi:nil="false"></maxTemp>
      <minTemp unit="C" xsi:nil="false"></minTemp>
    </temperature>

    <surface>
      <avgSurTemp unit="C" xsi:nil="false"></avgSurTemp>
      <maxSurTemp unit="C" xsi:nil="false"></maxSurTemp>
      <minSurTemp unit="C" xsi:nil="false"></minSurTemp>
    </surface>
    
    <solar>
      <avgSolRad unit="W/m²" xsi:nil="false"></avgSolRad>
      <maxSolRad unit="W/m²" xsi:nil="false"></maxSolRad>
      <minSolRad unit="W/m²" xsi:nil="false"></minSolRad>
    </solar>

    <humidity>
      <avgRelHum unit="%" xsi:nil="true"></avgRelHum>
    </humidity>
  </entry>

</climateData>

=== iTReprise/XML_Klimadaten_WS18-19/drafts/climateData_ohne_daten.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="climateData.xsl"?>
<!DOCTYPE climateData SYSTEM "climateData.dtd">
<climateData
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="/climateData.xsd"
  locationID="xxxxx">

  <longitude unit="decimal_degrees">xx</longitude>
  <latitude unit="decimal_degrees">xx</latitude>

  <entry date="yyyy.mm.dd" time="hh:mm" standard="UTC">
    <temperature>
      <curTemp unit="C" xsi:nil="false">xx</curTemp>
      <avgTemp unit="C" xsi:nil="false">xx</avgTemp>
      <maxTemp unit="C" xsi:nil="false">xx</maxTemp>
      <minTemp unit="C" xsi:nil="false">xx</minTemp>
    </temperature>

    <surface>
      <avgSurTemp unit="C" xsi:nil="false">xx</avgSurTemp>
      <maxSurTemp unit="C" xsi:nil="false">xx</maxSurTemp>
      <minSurTemp unit="C" xsi:nil="false">xx</minSurTemp>
    </surface>
    
    <solar>
      <avgSolRad unit="W/m²" xsi:nil="true"></avgSolRad>
      <maxSolRad unit="W/m²" xsi:nil="false">xx</maxSolRad>
      <minSolRad unit="W/m²" xsi:nil="false">xx</minSolRad>
    </solar>

    <humidity>
      <avgRelHum unit="%" xsi:nil="false">xx</avgRelHum>
    </humidity>
  </entry>

</climateData>
